import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { useState } from 'react';
import Newsletter from './newsletter';

const inter = Inter({ subsets: ['latin'] })

const callChatGPT = async (answers) => {
  console.log('call gpt', answers)
  const res = await fetch('/api/completion', {
    method: 'POST',
    body: JSON.stringify({ answers })
  }).then(res => res.json())
  console.log('res', res)
  return res.result
}

export default function Home() {
  const [answers, updateAnswer] = useState({
    answer1: '',
    answer2: '',
    answer3: '',
  })
  const [newsletter, saveNewsletter] = useState('')

  const [renderNewsletter, switchRenderNewsletter] = useState(false)

  const router = useRouter()
  const handleClick = (e) => {
    callChatGPT(answers).then((response) => {
      saveNewsletter(response);
      switchRenderNewsletter(true)
    })
  }
  const answerQuestion = (e, q) => {
    updateAnswer({ ...answers, [q]: e.target.value })
  }
  return (
  <>
    { renderNewsletter && <Newsletter newsletter={newsletter} switchRenderNewsletter={switchRenderNewsletter} /> }
    { !renderNewsletter &&
      <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
       <h3 style={{ cursor: 'pointer', marginLeft: '50px' }}>
           Nujen
       </h3>
      </div>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1 className={styles.title}>
            Newsletter Generator
          </h1>
          <p>
            Write a name:
          </p>
          <div className={styles.question}>
            <textarea onChange={(e) => answerQuestion(e, 'answer1')} rows='4' cols='50' value={ answers.answer1 } />
          </div>
          <p>
            Write a place:
          </p>
          <div className={styles.question}>
            <textarea onChange={(e) => answerQuestion(e, 'answer2')} rows='4' cols='50' value={ answers.answer2 } />
          </div>
          <p>
            Write an event:
          </p>
          <div className={styles.question}>
            <textarea onChange={(e) => answerQuestion(e,'answer3')} rows='4' cols='50' value={ answers.answer3 } />
          </div>
          <div style={{ display: 'flex', justifyContent: 'center'}}>
            <button className={styles.btn} onClick={handleClick}>
              Generate Newsletter
            </button>
          </div>
        </div>
      </main>
    </>
}
</>
  )
}
